### ISSUE TITLE
Android NDK

### ISSUE THREAD

**Issue by archimedeschess** [Witek902/Caissa#10]
When I compile with Android NDK (which uses the Clang compiler) by using the flag "-DUSE_ARM_NEON", I get the following error message:
```
backend/PackedNeuralNetwork.cpp:544:33: fatal error: no matching function for call to 'vaddq_s32'
val += vaddvq_s32(vaddq_s32(vaddq_s32(sumA, sumB, vaddq_s32(sumC, sumD));
```
I assume the line must look like this:
```
val += vaddvq_s32(vaddq_s32(vaddq_s32(sumA, sumB), vaddq_s32(sumC, sumD)));
```
Finally, an additional "#include \<cmath\>" is required in Evaluate.hpp.

With these changes, Caissa compiles smoothly with Android NDK.

**Comment by Witek902** [comment]
Fixed in fad51443a73be318485a3ac66c945d2b63ea813b. I don't get the error in Evaluate.hpp though. Which compiler are you using. Compiles fine on GGC 11.3 and Clang 14 for me
